version: "3.10"

services:
  vfadeev:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ~/prod/nginx/staticfiles/vfadeev/static:/src/app/static
      - ~/prod/vfadeev/src/:/src/
    command: sh -c "gunicorn -b 0.0.0.0:8000 --pythonpath /src main:app -w 1 --threads 1 --log-level=info"

  vfadeev-certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ~/prod/nginx/certbot/conf/vfadeev:/etc/letsencrypt
      - ~/prod/nginx/certbot/www/vfadeev:/var/www/certbot

networks:
  default:
    name: src_default
    external: true

