version: "3.10"

services:
  vfadeev:
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    build:
      context: .
    volumes:
      - /opt/prod/nginx/staticfiles/vfadeev/static:/src/app/static
      - /opt/prod/vfadeev:/src
    command: sh -c "gunicorn -b 0.0.0.0:8000 --pythonpath /src main:app -w 1 --threads 1 --log-level=info"

  vfadeev-certbot:
    image: certbot/certbot
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /opt/prod/nginx/certbot/conf:/etc/letsencrypt
      - /opt/prod/nginx/certbot/www:/var/www/certbot

networks:
  default:
    name: nginx_network
    external: true

