"""init migration.

Revision ID: 4c3342fa63be
Revises: 
Create Date: 2023-10-17 20:28:46.573493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3342fa63be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_contact_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=False))

    with op.batch_alter_table('social_contact_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_contact_model', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('location_contact_model', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
