"""blog views/likes/comments + oauth users

Revision ID: f91a99748b41
Revises: 3fb5dad5403a
Create Date: 2026-04-27 10:11:02.167551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91a99748b41'
down_revision = '3fb5dad5403a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_reaction')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
        batch_op.alter_column('hash_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_provider', ['provider', 'provider_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_provider', type_='unique')
        batch_op.alter_column('hash_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('email')
        batch_op.drop_column('provider_id')
        batch_op.drop_column('provider')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('views_count')

    op.drop_table('post_reaction')
    op.drop_table('blog_comment')
    # ### end Alembic commands ###
